In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'Signal': [1, 1, 0, 1, 0, 1],
    'Return': [0.04, -0.01, 0.02, 0.03, -0.05, 0.01],
    'VolumeSpike': [1, 0, 1, 1, 0, 1]
})

df

   Signal  Return  VolumeSpike
0       1    0.04            1
1       1   -0.01            0
2       0    0.02            1
3       1    0.03            1
4       0   -0.05            0
5       1    0.01            1

### **P(Returns > 0 | Signal =1, Vol spike = 1)**

In [5]:
shrink_condition = (df["Signal"] == 1) & (df["VolumeSpike"] == 1)

In [6]:
shrinked_df = df[shrink_condition]
shrinked_df

   Signal  Return  VolumeSpike
0       1    0.04            1
3       1    0.03            1
5       1    0.01            1

In [8]:
(shrinked_df["Return"] > 0).mean()

1.0