In [1]:
import pandas as pd

# Part 1: Loop Fundamentals | for, range(), and len(df)

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Stock": ["AAPL", "MSFT", "NVDA", "AMZN",
              "GOOG", "META", "TSLA", "AVGO"],
    "Price": [220, 510, 180, 225, 190, 700, 330, 300],
    "Volume": [1000, 1500, 2400, 1800, 900, 2100, 3000, 1600]
})

df

  Stock  Price  Volume
0  AAPL    220    1000
1  MSFT    510    1500
2  NVDA    180    2400
3  AMZN    225    1800
4  GOOG    190     900
5  META    700    2100
6  TSLA    330    3000
7  AVGO    300    1600

### Method A — **`len(df)`** and **`.iloc[i]`**

In [3]:
for i in range(len(df)):
    print(i)

0
1
2
3
4
5
6
7

In [4]:
for i in range(len(df)):
    print(df["Stock"].iloc[i])

AAPL
MSFT
NVDA
AMZN
GOOG
META
TSLA
AVGO

In [5]:
for i in range(len(df)):
    stock = df.iloc[i]["Stock"]
    price = df.iloc[i]["Price"]

    print(stock, price)

AAPL 220
MSFT 510
NVDA 180
AMZN 225
GOOG 190
META 700
TSLA 330
AVGO 300

`len(df)`

Returns 8, because there are eight rows.


`range(8)`

Produces 0, 1, 2, 3, 4, 5, 6, 7.


`iloc[i]`

Fetches the row at that numerical position.

In [6]:
for i in range(len(df)):
    stock = df["Stock"].iloc[i]
    price = df["Price"].iloc[i]

    print(stock, price)

AAPL 220
MSFT 510
NVDA 180
AMZN 225
GOOG 190
META 700
TSLA 330
AVGO 300

### Method B: `df.iterrows()`

In [7]:
for index, row in df.iterrows():
    print(row["Stock"], row["Price"])

AAPL 220
MSFT 510
NVDA 180
AMZN 225
GOOG 190
META 700
TSLA 330
AVGO 300

### Why use Method A more? | **Access to row positions**

In [8]:
filtered = df[df["Price"] > 200]

filtered

  Stock  Price  Volume
0  AAPL    220    1000
1  MSFT    510    1500
3  AMZN    225    1800
5  META    700    2100
6  TSLA    330    3000
7  AVGO    300    1600

In [9]:
filtered.index

Index([0, 1, 3, 5, 6, 7], dtype='int64')

In [10]:
for index, row in filtered.iterrows():
    print(index, row["Stock"])

0 AAPL
1 MSFT
3 AMZN
5 META
6 TSLA
7 AVGO

In [11]:
for i in range(len(filtered)):
    print(i, filtered.iloc[i]["Stock"])

0 AAPL
1 MSFT
2 AMZN
3 META
4 TSLA
5 AVGO

**Suppose you want the third row of filtered.**

In [12]:
filtered.iloc[2]       # AMZN — third row by position

Stock     AMZN
Price      225
Volume    1800
Name: 3, dtype: object

**Suppose you need the price difference between the current row and the previous row.**

In [13]:
for i in range(1, len(df)):
    
    current = df.iloc[i]["Price"]
    previous = df.iloc[i - 1]["Price"]
    change = current - previous

    print(change)

290
-330
45
-35
510
-370
-30

> Here, i - 1 makes accessing the previous row straightforward.  
> iterrows() does not automatically provide it.

# Part 2: Accessing different rows inside a loop

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Date": pd.date_range("2026-01-01", periods=8),
    "Price": [100, 104, 102, 108, 105, 112, 110, 118],
    "Volume": [1000, 1200, 900, 1500, 1100, 1800, 1400, 2000]
})

df

        Date  Price  Volume
0 2026-01-01    100    1000
1 2026-01-02    104    1200
2 2026-01-03    102     900
3 2026-01-04    108    1500
4 2026-01-05    105    1100
5 2026-01-06    112    1800
6 2026-01-07    110    1400
7 2026-01-08    118    2000

In [15]:
# 1. Current row
for i in range(len(df)):
    current_price = df.iloc[i]["Price"]
    print(current_price)

100
104
102
108
105
112
110
118

In [16]:
# 2. Previous row
# Start from i = 1, because the first row has no previous row.

for i in range(1, len(df)):
    current_price = df.iloc[i]["Price"]
    
    print(current_price)

104
102
108
105
112
110
118

In [17]:
# 3. Two rows earlier
# Start from i = 2, because you need two earlier rows to exist.

for i in range(2, len(df)):
    tminus3_price = df.iloc[i]["Price"]

    print(tminus3_price)

102
108
105
112
110
118

**Start at n if you want to go back n days**

In [18]:
# 3. Two rows earlier
# Start from i = 2, because you need two earlier rows to exist. 2-2 will take you to 0.

for i in range(2, len(df)):
    current_price = df.iloc[i]["Price"]
    tm2_price = df.iloc[i-2]["Price"]

    print(current_price, tm2_price)

102 100
108 104
105 102
112 108
110 105
118 112

In [19]:
# 1. Calculate the percentage price change between the current row and the previous row.

# Formula: (current_price / previous_price) - 1

for i in range (1, len(df)):
    t = df.iloc[i]["Price"]
    tm1 = df.iloc[i - 1]["Price"]
    ret = t / tm1 - 1

    print(ret)

0.040000000000000036
-0.019230769230769273
0.05882352941176472
-0.02777777777777779
0.06666666666666665
-0.017857142857142905
0.07272727272727275

In [20]:
# 2. Print the current price and the volume from two rows earlier.

for i in range (2, len(df)):
    price = df.iloc[i]["Price"]
    volume = df.iloc[i-2]["Volume"]

    print(price, volume)

102 1000
108 1200
105 900
112 1500
110 1100
118 1800

In [21]:
# 3. A strategy buys when today's price is greater than yesterday's price AND yesterday's volume was above 1,000. 
# Write the loop condition to check this. You do not need to implement the actual buying.

for i in range(1, len(df)):
    d = df.iloc[i]["Date"]
    t = df.iloc[i]["Price"]
    tm1 = df.iloc[i-1]["Price"]
    vol_m_1 = df.iloc[i-1]["Volume"]

    if t > tm1 and vol_m_1 > 1000:
        print(d, t, tm1, vol_m_1, "buy")

2026-01-06 00:00:00 112 105 1100 buy
2026-01-08 00:00:00 118 110 1400 buy

In [22]:
# 4. Calculate the three-row price change:

for i in range (3, len(df)):
    d = df.iloc[i]["Date"]
    current_price = df.iloc[i]["Price"]
    tm3_price = df.iloc[i-3]["Price"]

    ret_3d = current_price / tm3_price - 1

    print(d, ret_3d)

2026-01-04 00:00:00 0.08000000000000007
2026-01-05 00:00:00 0.009615384615384581
2026-01-06 00:00:00 0.0980392156862746
2026-01-07 00:00:00 0.0185185185185186
2026-01-08 00:00:00 0.12380952380952381

# Part 3: Collecting results into a DataFrame

### Step 1 — Create an empty list | Before the loop

In [23]:
results = []

### Step 2 — Store each calculated result | Inside the loop

In [24]:
for i in range (3, len(df)):
    d = df.iloc[i]["Date"]
    current_price = df.iloc[i]["Price"]
    tm3_price = df.iloc[i-3]["Price"]

    ret_3d = current_price / tm3_price - 1

    # print(d, ret_3d)

    results.append(ret_3d)

In [25]:
results

[0.08000000000000007,
 0.009615384615384581,
 0.0980392156862746,
 0.0185185185185186,
 0.12380952380952381]

### Step 3 — Build a DataFrame | After the loop

After the loop has finished, combine the lists and create a dataframe to store them:

In [26]:
result_df = pd.DataFrame({
    "Return_3D": results
})

In [27]:
result_df

   Return_3D
0   0.080000
1   0.009615
2   0.098039
3   0.018519
4   0.123810

### Full structure

In [28]:
# Step 1 — Create empty lists | Before the loop
results = []
dates = []

# Step 2 — Store each calculated result | Inside the loop
for i in range (3, len(df)):
    d = df.iloc[i]["Date"]
    current_price = df.iloc[i]["Price"]
    tm3_price = df.iloc[i-3]["Price"]

    ret_3d = current_price / tm3_price - 1

    # print(d, ret_3d)
    dates.append(d)
    results.append(ret_3d)

# Step 3 — Build a DataFrame | After the loop
result_df = pd.DataFrame({
    "Date": dates,
    "Return_3D": results
})

result_df

        Date  Return_3D
0 2026-01-04   0.080000
1 2026-01-05   0.009615
2 2026-01-06   0.098039
3 2026-01-07   0.018519
4 2026-01-08   0.123810

In [29]:
results = []

for i in range(1, len(df)):
    date = df.iloc[i]["Date"]
    price = df.iloc[i]["Price"]
    previous_price = df.iloc[i-1]["Price"]

    ret = price / previous_price - 1
    signal = 1 if ret > 0 else 0

    results.append([date, ret, signal])

# create dataframe using the list and `columns=[]`
result_df = pd.DataFrame(
    results,
    columns=["Date", "Return", "Signal"]
)

In [30]:
result_df

        Date    Return  Signal
0 2026-01-02  0.040000       1
1 2026-01-03 -0.019231       0
2 2026-01-04  0.058824       1
3 2026-01-05 -0.027778       0
4 2026-01-06  0.066667       1
5 2026-01-07 -0.017857       0
6 2026-01-08  0.072727       1

# Part 4: Nested loops

In [34]:
import pandas as pd

df = pd.DataFrame({
    "Date": pd.date_range("2026-01-01", periods=4),
    "AAPL": [100, 103, 101, 105],
    "MSFT": [200, 198, 202, 205],
    "NVDA": [150, 155, 153, 160]
})

df["Date"] = pd.to_datetime(df["Date"])
df = df.set_index("Date")

df

            AAPL  MSFT  NVDA
Date
2026-01-01   100   200   150
2026-01-02   103   198   155
2026-01-03   101   202   153
2026-01-04   105   205   160

In [42]:
### Part 1: Get the columns in a list
stocks = df.columns
results = []

stocks

Index(['AAPL', 'MSFT', 'NVDA'], dtype='object')

In [ ]:
### Part 2: Run the outer loop and access in inner loop

for stock in stocks:
    for i in range(1, len(df)):

        d = df.index[i]
        current_price = df.iloc[i][stock]
        previous_price = df.iloc[i - 1][stock]

        signal = 1  if current_price > previous_price else 0

        results.append([d, stock, signal])


results

[[Timestamp('2026-01-02 00:00:00'), 'AAPL', 1],
 [Timestamp('2026-01-03 00:00:00'), 'AAPL', 0],
 [Timestamp('2026-01-04 00:00:00'), 'AAPL', 1],
 [Timestamp('2026-01-02 00:00:00'), 'MSFT', 0],
 [Timestamp('2026-01-03 00:00:00'), 'MSFT', 1],
 [Timestamp('2026-01-04 00:00:00'), 'MSFT', 1],
 [Timestamp('2026-01-02 00:00:00'), 'NVDA', 1],
 [Timestamp('2026-01-03 00:00:00'), 'NVDA', 0],
 [Timestamp('2026-01-04 00:00:00'), 'NVDA', 1]]

In [44]:
### Part 3: Build the results df
results_df = pd.DataFrame(
    results,
    columns=["Date", "Stock", "Signal"]
)

results_df

        Date Stock  Signal
0 2026-01-02  AAPL       1
1 2026-01-03  AAPL       0
2 2026-01-04  AAPL       1
3 2026-01-02  MSFT       0
4 2026-01-03  MSFT       1
5 2026-01-04  MSFT       1
6 2026-01-02  NVDA       1
7 2026-01-03  NVDA       0
8 2026-01-04  NVDA       1

In [45]:
### Part 4: Pivot back to wide format
signal_df = results_df.pivot(index = "Date", columns= "Stock", values= "Signal")

signal_df

Stock       AAPL  MSFT  NVDA
Date
2026-01-02     1     0     1
2026-01-03     0     1     0
2026-01-04     1     1     1

In [47]:
### Full Structure

# Part 1: Get the columns in a list
stocks = df.columns
results = []

# Part 2: Run the outer loop and access in inner loop

for stock in stocks:
    for i in range(1, len(df)):

        d = df.index[i]
        current_price = df.iloc[i][stock]
        previous_price = df.iloc[i - 1][stock]

        signal = 1  if current_price > previous_price else 0

        results.append([d, stock, signal])

# Part 3: Build the results df
results_df = pd.DataFrame(
    results,
    columns=["Date", "Stock", "Signal"]
)

# Part 4: Pivot back to wide format
signal_df = results_df.pivot(index = "Date", columns= "Stock", values= "Signal")

signal_df

Stock       AAPL  MSFT  NVDA
Date
2026-01-02     1     0     1
2026-01-03     0     1     0
2026-01-04     1     1     1

# Part 5: Handling data in loops

### Handling missing data

In [51]:
df = pd.DataFrame({
    "Date": pd.date_range("2026-01-01", periods=5),
    "AAPL": [100, 105, None, 110, 115],
    "MSFT": [200, 198, 202, None, 205]
}).set_index("Date")

df

             AAPL   MSFT
Date
2026-01-01  100.0  200.0
2026-01-02  105.0  198.0
2026-01-03    NaN  202.0
2026-01-04  110.0    NaN
2026-01-05  115.0  205.0

In [65]:
# Skip invalid observations using continue

results = []

for stock in df.columns:
    for i in range(1,len(df)):
        d = df.index[i]
        current_price = df.iloc[i][stock]
        previous_price = df.iloc[i-1][stock]

        if pd.isna(current_price) or pd.isna(previous_price):
            continue

        ret = current_price / previous_price - 1

        results.append([d, stock, ret])

results_df = pd.DataFrame(results, columns=["Date", "Stock", "Returns"])

results_df

        Date Stock   Returns
0 2026-01-02  AAPL  0.050000
1 2026-01-05  AAPL  0.045455
2 2026-01-02  MSFT -0.010000
3 2026-01-03  MSFT  0.020202

In [66]:
results_df_wide = results_df.pivot(index="Date", columns="Stock", values="Returns")
results_df_wide

Stock           AAPL      MSFT
Date
2026-01-02  0.050000 -0.010000
2026-01-03       NaN  0.020202
2026-01-05  0.045455       NaN

### Different amounts of historical data

In [69]:
df = pd.DataFrame({
    "Date": pd.date_range("2026-01-01", periods=5),
    "AAPL": [100, 102, 104, 103, 106],
    "NEW": [None, None, 50, 52, 55]
}).set_index("Date")

df

            AAPL   NEW
Date
2026-01-01   100   NaN
2026-01-02   102   NaN
2026-01-03   104  50.0
2026-01-04   103  52.0
2026-01-05   106  55.0

In [73]:
results = []

for stock in df.columns:
    valid_prices = df[stock].dropna()

    if len(valid_prices) < 3:
        continue

    for i in range(1, len(df)):
        d = df.index[i]
        current_price = df.iloc[i][stock]
        previous_price = df.iloc[i-1][stock]

        if pd.isna(current_price) or pd.isna(previous_price):
            continue

        ret = current_price / previous_price - 1
        results.append([d, stock, ret])

results_df = pd.DataFrame(results, columns=["Date", "Stock", "Returns"])

results_df

        Date Stock   Returns
0 2026-01-02  AAPL  0.020000
1 2026-01-03  AAPL  0.019608
2 2026-01-04  AAPL -0.009615
3 2026-01-05  AAPL  0.029126
4 2026-01-04   NEW  0.040000
5 2026-01-05   NEW  0.057692

### Practise

In [77]:
### Practise
import yfinance as yf
import pandas as pd

tickers = ["IXN", "IXC", "URTH"]

# Fetch a buffer of calendar days, then keep the last 50 trading days
raw = yf.download(tickers, period="1y", auto_adjust=True, progress=False)
prices = raw["Close"].dropna(how="all").tail(250)
prices.tail()

Ticker            IXC         IXN        URTH
Date
2026-10-19  62.410000  139.259995  206.649994
2026-10-20  62.650002  138.770004  207.399994
2026-10-21  62.750000  141.240005  208.490005
2026-10-22  62.349998  136.119995  206.169998
2026-10-23  63.880001  136.970001  205.149994

In [78]:
prices.shape

(250, 3)

Skip stocks with fewer than 100 valid prices.

Calculate the 5-day return for each eligible stock.

Store the results in a DataFrame with Date, Stock, and Return_5D.

In [ ]:
results = []

for stock in prices.columns:

    valid_prices = prices[stock].dropna()

    if len(valid_prices) < 100:
        continue

    for i in range(5, len(prices)):
        d = prices.index[i]
        current_px = prices.iloc[i][stock]
        px_5d = prices.iloc[i-5][stock]

        if pd.isna(current_px) or pd.isna(px_5d):
            continue

        ret_5d = current_px / px_5d - 1

        results.append([d, stock, ret_5d])


results_df = pd.DataFrame(results, columns=["Date", "Stock", " Returns_5d"])

results_df.tail()
results_df.isna().sum()

Date           0
Stock          0
 Returns_5d    0
dtype: int64