In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Signal': [1,0,0,1,1,0],
    'Returns': [0.06, 0.02,-0.01,0,-0.01,0.02],
})

In [3]:
df

   Signal  Returns
0       1     0.06
1       0     0.02
2       0    -0.01
3       1     0.00
4       1    -0.01
5       0     0.02

### **P(Returns > 0 | Signal =1)**

In [4]:
# condition that shrinks universe: signal = 1
signal_condition = df['Signal'] == 1
df[signal_condition]

# lets store this required universe in a separate df
signal_df = df[signal_condition]
signal_df

   Signal  Returns
0       1     0.06
3       1     0.00
4       1    -0.01

In [5]:
# probability where returns is > 0 is sum/total
signal_df["Returns"]>0

# True = 1 nad False = 0 | sum of True / total can be calculated by mean | mean = (1 + 0 + 0) / 3 which is also the probability required.
(signal_df["Returns"]>0).mean()

np.float64(0.3333333333333333)

### **E(Returns | Signal = 1)**

In [6]:
# get the universe
signal = df["Signal"] == 1
signal_df = df[signal]
signal_df

   Signal  Returns
0       1     0.06
3       1     0.00
4       1    -0.01

Expected value is the probability weighted sum  
here the events are assumed to be equal likely  
so we can calculate average

r1 * 1/3 + r2 * 1/3 + r3 *1/3

same thing

In [7]:
signal_df["Returns"].mean()

np.float64(0.016666666666666666)

### **Variance of the above**

In [8]:
signal_df["Returns"].var()

np.float64(0.0014333333333333333)

### **Standard deviation**

In [9]:
signal_df["Returns"].std()

np.float64(0.03785938897200183)

# Summary

### **P(Returns > 0 | Signal =1)**

#### Create the universe

In [10]:
# First create the universe
# 1. start from the condition

signal = df["Signal"] == 1

# 2. then create the universe in a separate df
signal_df = df[signal]


signal_df

   Signal  Returns
0       1     0.06
3       1     0.00
4       1    -0.01

##### Then calculate the required stuff

In [11]:
# for probability we need to get the cases 1st
signal_df["Returns"]>0

0     True
3    False
4    False
Name: Returns, dtype: bool

In [12]:
# then we take advantage of True = 1 in pandas boolean series
(signal_df["Returns"]>0).mean()

np.float64(0.3333333333333333)

### **E(Returns | Signal = 1)**

In [13]:
# universe is in signal_df
signal_df["Returns"].mean()

np.float64(0.016666666666666666)

### **Standard deviation**

In [14]:
signal_df["Returns"].std()

np.float64(0.03785938897200183)

## **Shortcut**

### **P(Returns > 0 | Signal =1)**

In [15]:
# Universe
df.loc[df["Signal"] == 1, "Returns"]

0    0.06
3    0.00
4   -0.01
Name: Returns, dtype: float64

### **This one's tricky:**

In [16]:
# Probability

# get the boolean format
df.loc[df["Signal"] == 1, "Returns"] > 0  # universe then return column then >0 condition

# then cal the mean for probability
(df.loc[df["Signal"] == 1, "Returns"]>0).mean()

np.float64(0.3333333333333333)

In [17]:
# EV
df.loc[df["Signal"] == 1, "Returns"].mean()

np.float64(0.016666666666666666)

In [18]:
# Standard dev
df.loc[df["Signal"] == 1, "Returns"].std()

np.float64(0.03785938897200183)