In [1]:
import pandas as pd

## **Part 1: loc vs iloc**

In [2]:
df = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT", "GOOG", "AMZN"],
    "Price": [200, 420, 175, 190],
    "Return": [0.02, -0.01, 0.03, 0.01]
})

In [3]:
df

  Ticker  Price  Return
0   AAPL    200    0.02
1   MSFT    420   -0.01
2   GOOG    175    0.03
3   AMZN    190    0.01

Rule  
loc = labels  
iloc = integer positions

In [4]:
df.loc[1, "Price"]

420

row label 1, column label "Price"

In [5]:
df.iloc[1, 1]

420

second row, second column

#### Slicing

iloc excludes the last number index

In [6]:
df.iloc[1:3]

  Ticker  Price  Return
1   MSFT    420   -0.01
2   GOOG    175    0.03

returns rows 1,2  
excudes the last number index

**but loc behaves differently**  

it includes the last number index

In [7]:
df.loc[1:3]

  Ticker  Price  Return
1   MSFT    420   -0.01
2   GOOG    175    0.03
3   AMZN    190    0.01

**Important point**  
>iloc slicing excludes the endpoint.  
>loc slicing includes the endpoint.

### **Understanding the comma**  
df.iloc[rows, columns]

before comma = rows  
after comma = columns

In [8]:
df.iloc[0:2, 1:3]

   Price  Return
0    200    0.02
1    420   -0.01

rows 0, 1  
columns 1,2

### **Understanding :**
: means everything

In [9]:
df.iloc[:, 1]

0    200
1    420
2    175
3    190
Name: Price, dtype: int64

all rows, column 1

In [10]:
df.iloc[1, :]

Ticker    MSFT
Price      420
Return   -0.01
Name: 1, dtype: object

row 1, all columns

**Important point**  

**df.iloc[ROWS, COLUMNS]**

### **Boolean filtering**

In [11]:
df.loc[df["Return"] > 0]

  Ticker  Price  Return
0   AAPL    200    0.02
2   GOOG    175    0.03
3   AMZN    190    0.01

can select columns inside a **list**

In [12]:
df.loc[df["Return"] > 0, ["Ticker", "Return"]]

  Ticker  Return
0   AAPL    0.02
2   GOOG    0.03
3   AMZN    0.01

# **Part 2: Missing Data**

### 1. isna()

In [13]:
df = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT", "GOOG", "AMZN"],
    "Price": [190, None, 175, None],
    "Return": [0.02, -0.01, None, 0.03]
})

In [14]:
df

  Ticker  Price  Return
0   AAPL  190.0    0.02
1   MSFT    NaN   -0.01
2   GOOG  175.0     NaN
3   AMZN    NaN    0.03

Returns a DataFrame of True/False:

In [15]:
df.isna()

   Ticker  Price  Return
0   False  False   False
1   False   True   False
2   False  False    True
3   False   True   False

Count missing values per column [**Most Useful**]:

In [16]:
df.isna().sum()

Ticker    0
Price     2
Return    1
dtype: int64

Check whether a particular column is missing

In [17]:
df["Price"].isna()

0    False
1     True
2    False
3     True
Name: Price, dtype: bool

### 2. dropna()

#### df.dropnna()

Removes **rows** containing at least one missing value.

In [18]:
df.dropna()

  Ticker  Price  Return
0   AAPL  190.0    0.02

#### df.dropna(axis=1)

Drop columns with missing values

In [19]:
df.dropna(axis=1)

  Ticker
0   AAPL
1   MSFT
2   GOOG
3   AMZN

#### Axis use
**axis = 1 → check columns / operate column wise**

**Remember:**  
axis=0 → rows (default)  
axis=1 → columns

### 3. fillna()

Instead of deleting missing observations, we can replace them.

In [20]:
df["Price"].fillna(0)

0    190.0
1      0.0
2    175.0
3      0.0
Name: Price, dtype: float64

Fill with the mean

In [21]:
df["Price"].fillna(df["Price"].mean())

0    190.0
1    182.5
2    175.0
3    182.5
Name: Price, dtype: float64

### 4. ffill()

In [22]:
df2 = pd.DataFrame({
    "Date": ["Jan 10", "Jan 11", "Jan 12", "Jan 13", "Jan 14"],
    "Price": [120, 140,None,None, 100]
})

In [23]:
df2

     Date  Price
0  Jan 10  120.0
1  Jan 11  140.0
2  Jan 12    NaN
3  Jan 13    NaN
4  Jan 14  100.0

In [24]:
#df2.isna()

In [25]:
df2.ffill()

     Date  Price
0  Jan 10  120.0
1  Jan 11  140.0
2  Jan 12  140.0
3  Jan 13  140.0
4  Jan 14  100.0

It carries the previous known value forward.

### 5. bfill()

In [26]:
df2["Price"].bfill()

0    120.0
1    140.0
2    100.0
3    100.0
4    100.0
Name: Price, dtype: float64

It takes the next known value backward.

In [27]:
df2.bfill()

     Date  Price
0  Jan 10  120.0
1  Jan 11  140.0
2  Jan 12  100.0
3  Jan 13  100.0
4  Jan 14  100.0

In [28]:
df2.dropna()

     Date  Price
0  Jan 10  120.0
1  Jan 11  140.0
4  Jan 14  100.0

In [29]:
df2.dropna(axis = 1)

     Date
0  Jan 10
1  Jan 11
2  Jan 12
3  Jan 13
4  Jan 14

# **Part 3: Duplicates and Bad Data**

In [30]:
df3 = pd.DataFrame({
    "Date": ["Mar 5 2026", "Mar 6 2026", "Mar 6 2026","Mar 7 2026", "Mar 8 2026", "Mar 9 2026", "Mar 10 2026", "Mar 11 2026"],
    "JPM": [300, 310, 310, 340, 305, 299, None, 306],
    "AAPL": [190, 180, 180, 170, 185, 189, 195, 199],
    "GOOG": [175, 170, 170, 183, 190, 194, 188, 185],
    "AAPL": [190, 180, 180, 170, 185, 189, 195, 199],
    "TSLA": [350, 340, 340, 300, 290, 280, 295, 320]

})

In [31]:
df3

          Date    JPM  AAPL  GOOG  TSLA
0   Mar 5 2026  300.0   190   175   350
1   Mar 6 2026  310.0   180   170   340
2   Mar 6 2026  310.0   180   170   340
3   Mar 7 2026  340.0   170   183   300
4   Mar 8 2026  305.0   185   190   290
5   Mar 9 2026  299.0   189   194   280
6  Mar 10 2026    NaN   195   188   295
7  Mar 11 2026  306.0   199   185   320

**cant create a dictionary with 2 same keys**

### 1. duplicated()

In [32]:
df3.duplicated()

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [33]:
df3.duplicated(subset= ["Date"])

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [34]:
df3.duplicated(subset= ["JPM"])

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
dtype: bool

### 2. drop_duplicates()
Removes duplicate rows.

In [35]:
df3.drop_duplicates()

          Date    JPM  AAPL  GOOG  TSLA
0   Mar 5 2026  300.0   190   175   350
1   Mar 6 2026  310.0   180   170   340
3   Mar 7 2026  340.0   170   183   300
4   Mar 8 2026  305.0   185   190   290
5   Mar 9 2026  299.0   189   194   280
6  Mar 10 2026    NaN   195   188   295
7  Mar 11 2026  306.0   199   185   320

In [36]:
df3.drop_duplicates(keep="last")

          Date    JPM  AAPL  GOOG  TSLA
0   Mar 5 2026  300.0   190   175   350
2   Mar 6 2026  310.0   180   170   340
3   Mar 7 2026  340.0   170   183   300
4   Mar 8 2026  305.0   185   190   290
5   Mar 9 2026  299.0   189   194   280
6  Mar 10 2026    NaN   195   188   295
7  Mar 11 2026  306.0   199   185   320

### 3. Sorting and index problems

In [37]:
df4 = df3.copy()

In [38]:
df4.sort_values(by = "Date")

          Date    JPM  AAPL  GOOG  TSLA
6  Mar 10 2026    NaN   195   188   295
7  Mar 11 2026  306.0   199   185   320
0   Mar 5 2026  300.0   190   175   350
1   Mar 6 2026  310.0   180   170   340
2   Mar 6 2026  310.0   180   170   340
3   Mar 7 2026  340.0   170   183   300
4   Mar 8 2026  305.0   185   190   290
5   Mar 9 2026  299.0   189   194   280

In [39]:
df4["Date"] = pd.to_datetime(df4["Date"])

In [40]:
df4

        Date    JPM  AAPL  GOOG  TSLA
0 2026-03-05  300.0   190   175   350
1 2026-03-06  310.0   180   170   340
2 2026-03-06  310.0   180   170   340
3 2026-03-07  340.0   170   183   300
4 2026-03-08  305.0   185   190   290
5 2026-03-09  299.0   189   194   280
6 2026-03-10    NaN   195   188   295
7 2026-03-11  306.0   199   185   320

In [41]:
df4 = df4.sort_values("Date").set_index("Date")

In [42]:
df4

              JPM  AAPL  GOOG  TSLA
Date
2026-03-05  300.0   190   175   350
2026-03-06  310.0   180   170   340
2026-03-06  310.0   180   170   340
2026-03-07  340.0   170   183   300
2026-03-08  305.0   185   190   290
2026-03-09  299.0   189   194   280
2026-03-10    NaN   195   188   295
2026-03-11  306.0   199   185   320

In [43]:
df4.index.tolist()

[Timestamp('2026-03-05 00:00:00'),
 Timestamp('2026-03-06 00:00:00'),
 Timestamp('2026-03-06 00:00:00'),
 Timestamp('2026-03-07 00:00:00'),
 Timestamp('2026-03-08 00:00:00'),
 Timestamp('2026-03-09 00:00:00'),
 Timestamp('2026-03-10 00:00:00'),
 Timestamp('2026-03-11 00:00:00')]

In [44]:
df4 = df4.reset_index()

In [45]:
# 1. Reset index (if Date is currently the index)
df4 = df4.reset_index()

# 2. Ensure Date is datetime
df4["Date"] = pd.to_datetime(df4["Date"])

# 3. Sort chronologically
df4 = df4.sort_values("Date")

# 4. Remove duplicate dates (keep first occurrence)
df4 = df4.drop_duplicates(subset="Date", keep="first")

# 5. Set Date as index
df4 = df4.set_index("Date")

In [46]:
df4

            index    JPM  AAPL  GOOG  TSLA
Date
2026-03-05      0  300.0   190   175   350
2026-03-06      1  310.0   180   170   340
2026-03-07      3  340.0   170   183   300
2026-03-08      4  305.0   185   190   290
2026-03-09      5  299.0   189   194   280
2026-03-10      6    NaN   195   188   295
2026-03-11      7  306.0   199   185   320

In [47]:
df = pd.DataFrame({
    "Date": ["Jan1", "Jan2", "Jan2", "Jan3", "Jan3"],
    "Ticker": ["A", "A", "A", "B", "B"],
    "Price": [100, 102, 102, 50, 51]
})

In [48]:
df

   Date Ticker  Price
0  Jan1      A    100
1  Jan2      A    102
2  Jan2      A    102
3  Jan3      B     50
4  Jan3      B     51

In [49]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

**How would you identify all repeated Date–Ticker combinations, including their first occurrences?**

In [50]:
df.duplicated(subset=['Date', 'Ticker'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

First occurence is always False

In [51]:
df.drop_duplicates()

   Date Ticker  Price
0  Jan1      A    100
1  Jan2      A    102
3  Jan3      B     50
4  Jan3      B     51

In [52]:
df.drop_duplicates(subset=['Ticker'])

   Date Ticker  Price
0  Jan1      A    100
3  Jan3      B     50

**Why is sorting by date important before calculating daily returns?**

so that its in the right chronological order

# **Part 4: Combining datasets**

In [53]:
prices = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT", "NVDA", "AAPL"],
    "Date": ["2026-01-01", "2026-01-01",
             "2026-01-01", "2026-01-02"],
    "Price": [250, 420, 140, 255]
})

prices

  Ticker        Date  Price
0   AAPL  2026-01-01    250
1   MSFT  2026-01-01    420
2   NVDA  2026-01-01    140
3   AAPL  2026-01-02    255

In [54]:
weights = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT", "GOOGL"],
    "Weight": [0.4, 0.35, 0.25]
})

weights

  Ticker  Weight
0   AAPL    0.40
1   MSFT    0.35
2  GOOGL    0.25

### **merge() — combine using matching columns**

In [55]:
result = prices.merge(weights, on="Ticker", how="left")

result

  Ticker        Date  Price  Weight
0   AAPL  2026-01-01    250    0.40
1   MSFT  2026-01-01    420    0.35
2   NVDA  2026-01-01    140     NaN
3   AAPL  2026-01-02    255    0.40

- **on**="Ticker" — the **common column** used to match rows.

- **how**="left" — keep every row from prices.

- GOOGL doesn't appear in the output because it isn't present in prices.

### **join() — combine using the index**

In [56]:
prices_by_ticker = prices.set_index("Ticker")
weights_by_ticker = weights.set_index("Ticker")

result = prices_by_ticker.join(weights_by_ticker,how="left")

result

              Date  Price  Weight
Ticker
AAPL    2026-01-01    250    0.40
AAPL    2026-01-02    255    0.40
MSFT    2026-01-01    420    0.35
NVDA    2026-01-01    140     NaN

The key difference:
>- merge() usually matches using columns.
>- join() usually matches using the index of each DataFrame.

### **concat() — stack or place datasets together**

In [57]:
jan_prices = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT"],
    "Price": [250, 420]
})

feb_prices = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT"],
    "Price": [255, 430]
})

In [58]:
jan_prices

  Ticker  Price
0   AAPL    250
1   MSFT    420

In [59]:
feb_prices

  Ticker  Price
0   AAPL    255
1   MSFT    430

In [60]:
all_prices = pd.concat(
    [jan_prices, feb_prices],
    axis=0,
    ignore_index=True
)

In [61]:
all_prices

  Ticker  Price
0   AAPL    250
1   MSFT    420
2   AAPL    255
3   MSFT    430

### **Merging on multiple columns**

In [62]:
prices = pd.DataFrame({
    "Date": ["2026-01-01", "2026-01-02", "2026-01-01"],
    "Ticker": ["AAPL", "AAPL", "MSFT"],
    "Price": [250, 255, 420]
})

factors = pd.DataFrame({
    "Date": ["2026-01-01", "2026-01-02"],
    "Ticker": ["AAPL", "MSFT"],
    "Factor": [0.8, 0.6]
})

In [63]:
prices

         Date Ticker  Price
0  2026-01-01   AAPL    250
1  2026-01-02   AAPL    255
2  2026-01-01   MSFT    420

In [64]:
factors

         Date Ticker  Factor
0  2026-01-01   AAPL     0.8
1  2026-01-02   MSFT     0.6

In [65]:
result = prices.merge(
    factors,
    on=["Date", "Ticker"],
    how="left"
)

In [66]:
result

         Date Ticker  Price  Factor
0  2026-01-01   AAPL    250     0.8
1  2026-01-02   AAPL    255     NaN
2  2026-01-01   MSFT    420     NaN

### Detecting duplicates

In [67]:
prices = pd.DataFrame({
    "Date": ["2026-01-01", "2026-01-01"],
    "Ticker": ["AAPL", "MSFT"],
    "Price": [250, 420]
})

factors = pd.DataFrame({
    "Date": ["2026-01-01", "2026-01-01", "2026-01-01"],
    "Ticker": ["AAPL", "AAPL", "MSFT"],
    "Factor": [0.8, 0.9, 0.6]
})

In [68]:
prices

         Date Ticker  Price
0  2026-01-01   AAPL    250
1  2026-01-01   MSFT    420

In [69]:
factors

         Date Ticker  Factor
0  2026-01-01   AAPL     0.8
1  2026-01-01   AAPL     0.9
2  2026-01-01   MSFT     0.6

In [70]:
factors[["Date", "Ticker"]].duplicated()

0    False
1     True
2    False
dtype: bool

In [71]:
factors[["Date", "Ticker"]].duplicated().sum()

1

### Summary of Joining data - mini project

In [72]:
import pandas as pd

prices = pd.DataFrame({
    "Date": ["2026-01-01", "2026-01-01", "2026-01-02", "2026-01-02"],
    "Ticker": ["AAPL", "MSFT", "AAPL", "MSFT"],
    "Price": [250, 420, 255, 425]
})

weights = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT"],
    "Weight": [0.6, 0.4]
})

factors = pd.DataFrame({
    "Date": ["2026-01-01", "2026-01-01", "2026-01-02"],
    "Ticker": ["AAPL", "MSFT", "AAPL"],
    "Momentum": [0.8, 0.3, 0.9]
})

In [73]:
prices

         Date Ticker  Price
0  2026-01-01   AAPL    250
1  2026-01-01   MSFT    420
2  2026-01-02   AAPL    255
3  2026-01-02   MSFT    425

In [74]:
weights

  Ticker  Weight
0   AAPL     0.6
1   MSFT     0.4

In [75]:
factors

         Date Ticker  Momentum
0  2026-01-01   AAPL       0.8
1  2026-01-01   MSFT       0.3
2  2026-01-02   AAPL       0.9

In [76]:
# Q1. Merge prices with weights using Ticker. Keep every price row.

result = prices.merge(weights, on ="Ticker", how = "left")

result

         Date Ticker  Price  Weight
0  2026-01-01   AAPL    250     0.6
1  2026-01-01   MSFT    420     0.4
2  2026-01-02   AAPL    255     0.6
3  2026-01-02   MSFT    425     0.4

In [77]:
# Q2. Merge the result with factors using both Date and Ticker. Keep every price row.

result2 = result.merge(factors, on = ["Date" , "Ticker"], how = "left")

result2

         Date Ticker  Price  Weight  Momentum
0  2026-01-01   AAPL    250     0.6       0.8
1  2026-01-01   MSFT    420     0.4       0.3
2  2026-01-02   AAPL    255     0.6       0.9
3  2026-01-02   MSFT    425     0.4       NaN

#### indicator — find unmatched records

In [78]:
result3 = result.merge(
    factors,
    on=["Date", "Ticker"],
    how="left",
    indicator=True
)

result3

         Date Ticker  Price  Weight  Momentum     _merge
0  2026-01-01   AAPL    250     0.6       0.8       both
1  2026-01-01   MSFT    420     0.4       0.3       both
2  2026-01-02   AAPL    255     0.6       0.9       both
3  2026-01-02   MSFT    425     0.4       NaN  left_only

In [79]:
result3[result3["_merge"] != "both"]

         Date Ticker  Price  Weight  Momentum     _merge
3  2026-01-02   MSFT    425     0.4       NaN  left_only

In [80]:
result4 = result.merge(
    factors,
    on=["Date", "Ticker"],
    how="left",
    validate="one_to_one"
)

result4

         Date Ticker  Price  Weight  Momentum
0  2026-01-01   AAPL    250     0.6       0.8
1  2026-01-01   MSFT    420     0.4       0.3
2  2026-01-02   AAPL    255     0.6       0.9
3  2026-01-02   MSFT    425     0.4       NaN

# **Part 5: Grouping**

In [81]:
import pandas as pd

df = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT", "NVDA", "AAPL", "MSFT", "NVDA"],
    "Sector": ["Tech", "Tech", "Tech", "Tech", "Tech", "Tech"],
    "Date": ["Day1", "Day1", "Day1", "Day2", "Day2", "Day2"],
    "Return": [0.02, 0.01, 0.04, -0.01, 0.03, 0.02]
})

df

  Ticker Sector  Date  Return
0   AAPL   Tech  Day1    0.02
1   MSFT   Tech  Day1    0.01
2   NVDA   Tech  Day1    0.04
3   AAPL   Tech  Day2   -0.01
4   MSFT   Tech  Day2    0.03
5   NVDA   Tech  Day2    0.02

In [ ]:
df.groupby("Ticker")["Return"].mean() #*

Ticker
AAPL    0.005
MSFT    0.020
NVDA    0.030
Name: Return, dtype: float64

In [ ]:
df.groupby("Sector")["Return"].agg(["mean", "std", "count"])     #*

            mean       std  count
Sector
Tech    0.018333  0.017224      6

In [ ]:
df["Stock_Mean"] = df.groupby("Ticker")["Return"].transform("mean")  #*

In [85]:
df

  Ticker Sector  Date  Return  Stock_Mean
0   AAPL   Tech  Day1    0.02       0.005
1   MSFT   Tech  Day1    0.01       0.020
2   NVDA   Tech  Day1    0.04       0.030
3   AAPL   Tech  Day2   -0.01       0.005
4   MSFT   Tech  Day2    0.03       0.020
5   NVDA   Tech  Day2    0.02       0.030

In [86]:
# Write code to calculate the average Return for each Date.

df.groupby("Date")["Return"].mean()

Date
Day1    0.023333
Day2    0.013333
Name: Return, dtype: float64

### groupby() with multiple columns

In [87]:
df.groupby(["Ticker", "Date"])["Return"].mean()

Ticker  Date
AAPL    Day1    0.02
        Day2   -0.01
MSFT    Day1    0.01
        Day2    0.03
NVDA    Day1    0.04
        Day2    0.02
Name: Return, dtype: float64

In [88]:
# You want a summary of each sector's average and maximum return. Which pandas method would you use, and write the code.
df.groupby("Sector")["Return"].agg(["mean","max"])

            mean   max
Sector
Tech    0.018333  0.04

In [89]:
import pandas as pd

df = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT", "NVDA", "AAPL", "MSFT", "NVDA"],
    "Sector": ["Tech", "Tech", "Tech", "Tech", "Tech", "Tech"],
    "Date": ["Day1", "Day1", "Day1", "Day2", "Day2", "Day2"],
    "Return": [0.02, 0.01, 0.04, -0.01, 0.03, 0.02],
    "Volume": [200, 400, 890, 500, 350, 780]

})

df

  Ticker Sector  Date  Return  Volume
0   AAPL   Tech  Day1    0.02     200
1   MSFT   Tech  Day1    0.01     400
2   NVDA   Tech  Day1    0.04     890
3   AAPL   Tech  Day2   -0.01     500
4   MSFT   Tech  Day2    0.03     350
5   NVDA   Tech  Day2    0.02     780

In [90]:
df.groupby("Sector")[["Return", "Volume"]].mean()

          Return  Volume
Sector
Tech    0.018333   520.0

In [ ]:
df.groupby("Ticker")[["Return", "Volume"]].agg(["mean","std","max","min"])  #*

       Return                       Volume
         mean       std   max   min   mean         std  max  min
Ticker
AAPL    0.005  0.021213  0.02 -0.01  350.0  212.132034  500  200
MSFT    0.020  0.014142  0.03  0.01  375.0   35.355339  400  350
NVDA    0.030  0.014142  0.04  0.02  835.0   77.781746  890  780

# **Part 6: Reshaping Data**

In [95]:
import pandas as pd

df = pd.DataFrame({
    "Date": ["Day1", "Day1", "Day2", "Day2"],
    "Ticker": ["AAPL", "MSFT", "AAPL", "MSFT"],
    "Price": [250, 420, 255, 425]
})

df

   Date Ticker  Price
0  Day1   AAPL    250
1  Day1   MSFT    420
2  Day2   AAPL    255
3  Day2   MSFT    425

In [96]:
wide = df.pivot(index="Date", columns="Ticker", values="Price")

wide

Ticker  AAPL  MSFT
Date
Day1     250   420
Day2     255   425

In [103]:
# how to remove duplicate values for the same index?
wide.index.duplicated(keep='first')                         # what u want to remove
wide = wide[~wide.index.duplicated(keep='first')]


# OR

wide = wide.groupby(level=0).mean()    # or .last(), .first(), .sum(), .median()

# **Part 7: Data manipulation tools**

In [104]:
df = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT", "NVDA", "AAPL", "MSFT", "NVDA"],
    "Sector": ["Tech", "Tech", "Tech", "Tech", "Tech", "Tech"],
    "Date": ["Day1", "Day1", "Day1", "Day2", "Day2", "Day2"],
    "Return": [0.02, 0.01, 0.04, -0.01, 0.03, 0.02],
    "Volume": [200, 400, 890, 500, 350, 780]

})

df

  Ticker Sector  Date  Return  Volume
0   AAPL   Tech  Day1    0.02     200
1   MSFT   Tech  Day1    0.01     400
2   NVDA   Tech  Day1    0.04     890
3   AAPL   Tech  Day2   -0.01     500
4   MSFT   Tech  Day2    0.03     350
5   NVDA   Tech  Day2    0.02     780

In [107]:
# 1) apply() — apply a function

df["Return_Pct"] = df["Return"].apply(lambda x: x * 100)

Quant tip: Prefer vectorized operations like df["Return"] * 100 over apply() when possible; they're usually faster and clearer.

In [110]:
# 2) query() — filter rows cleanly

df.query("Return > 0.02")

  Ticker Sector  Date  Return  Volume  Return_Pct
2   NVDA   Tech  Day1    0.04     890         4.0
4   MSFT   Tech  Day2    0.03     350         3.0

In [113]:
df.query("Return > 0.02 and Volume > 400")

  Ticker Sector  Date  Return  Volume  Return_Pct
2   NVDA   Tech  Day1    0.04     890         4.0

In [115]:
# Equivalent boolean indexing:

df[(df["Return"] > 0.02) & (df["Volume"] > 400)]

  Ticker Sector  Date  Return  Volume  Return_Pct
2   NVDA   Tech  Day1    0.04     890         4.0

Use query() for readable filters; boolean indexing is more flexible for complex expressions.

In [117]:
# 3) Sorting and index management

df.sort_values("Date")                 # Sort by date
df.sort_values("Return", ascending=False)  # Highest return first
df.set_index("Date")                   # Date becomes index
df.reset_index()                       # Index becomes a column
df.rename(columns={"Return": "Returns"})  # Rename a column

  Ticker Sector  Date  Returns  Volume  Return_Pct
0   AAPL   Tech  Day1     0.02     200         2.0
1   MSFT   Tech  Day1     0.01     400         1.0
2   NVDA   Tech  Day1     0.04     890         4.0
3   AAPL   Tech  Day2    -0.01     500        -1.0
4   MSFT   Tech  Day2     0.03     350         3.0
5   NVDA   Tech  Day2     0.02     780         2.0

In [119]:
# Practise

df = pd.DataFrame({
    "Ticker": ["AAPL", "MSFT", "JPM", "AAPL"],
    "Return": [0.03, -0.01, 0.025, 0.01],
    "Volume": [2000000, 1500000, 900000, 2500000]
})

df

  Ticker  Return   Volume
0   AAPL   0.030  2000000
1   MSFT  -0.010  1500000
2    JPM   0.025   900000
3   AAPL   0.010  2500000

In [122]:
# Filter rows where Return is positive and Volume exceeds 1,000,000. Write the code.

df.query("Return > 0 and Volume > 1000000")

  Ticker  Return   Volume
0   AAPL    0.03  2000000
3   AAPL    0.01  2500000

In [123]:
# Create a new column Return_Pct by multiplying Return by 100. Write a vectorized expression.

df["Return_Pct"] = df["Return"]*100
df

  Ticker  Return   Volume  Return_Pct
0   AAPL   0.030  2000000         3.0
1   MSFT  -0.010  1500000        -1.0
2    JPM   0.025   900000         2.5
3   AAPL   0.010  2500000         1.0

In [125]:
df.sort_values(by = "Return", ascending = False)

  Ticker  Return   Volume  Return_Pct
0   AAPL   0.030  2000000         3.0
2    JPM   0.025   900000         2.5
3   AAPL   0.010  2500000         1.0
1   MSFT  -0.010  1500000        -1.0

# Part 8 — Mini-project: Build a financial data pipeline

In [127]:
import pandas as pd

prices = pd.DataFrame({
    "Date": ["2026-01-02", "2026-01-01", "2026-01-01",
             "2026-01-02", "2026-01-03"],
    "Ticker": ["AAPL", "AAPL", "MSFT", "AAPL", "MSFT"],
    "Price": [255, 250, 420, 255, None]
})

prices

         Date Ticker  Price
0  2026-01-02   AAPL  255.0
1  2026-01-01   AAPL  250.0
2  2026-01-01   MSFT  420.0
3  2026-01-02   AAPL  255.0
4  2026-01-03   MSFT    NaN