In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame({
    'Signal': [1,0,0,1,1,0,1,0],
    'Returns': [0.06, 0.02,-0.03,0,-0.01,0.02,0.02,0.01],
})

In [5]:
df

   Signal  Returns
0       1     0.06
1       0     0.02
2       0    -0.03
3       1     0.00
4       1    -0.01
5       0     0.02
6       1     0.02
7       0     0.01

### **P(Returns > 0 | Signal =1)**

In [9]:
condition = df["Signal"] == 1
df[condition]

   Signal  Returns
0       1     0.06
3       1     0.00
4       1    -0.01
6       1     0.02

In [13]:
shrinked_df = df[condition]

(shrinked_df["Returns"]>0).mean()

0.5

### **P(Signal = 1 | Returns > 0)**

In [14]:
# Byesian
condition2 = df["Returns"] > 0

shrinked_df2 = df[condition2]
shrinked_df2

   Signal  Returns
0       1     0.06
1       0     0.02
5       0     0.02
6       1     0.02
7       0     0.01

In [15]:
shrinked_df2["Signal"] == 1
(shrinked_df2["Signal"] == 1).mean()

0.4